### ISSUE TITLE
Iphone Compatibility

### ISSUE THREAD

**Issue by MilapKundalia** [jumartin/Calendar#1]
Hello Julien,

Thanks for this awesome Calendar
Just wanted to ask you will there be update in your control for IPhone Compatibility??

Thanks
Milap

**Comment by jumartin** [comment]
Hi Milap,
As you'll see, I've started to work on this and pushed a new branch. However I don't have much time right now to spend on this project so please be patient!

**Comment by d4kr** [comment]
Hi, thanks for the works you do, any timing/planning for the, already started, iphone version? Thanks, Dave

**Comment by tibnew** [comment]
I would be great if it worked for iPhone too. Keep up the great work!)
