### ISSUE TITLE
Limiting day/week view start size

### ISSUE THREAD

**Issue by pulimento** [jumartin/Calendar#10]
Hi Julien. First of all, thanks for your good work here, saved me lots of time.

I can't limit properly the starting hour of a MGCDayPlannerView. I want to limit the view so users can't scroll before 08.00 AM, for example. In my current app, really makes no sense that users plan activities between 00.00 and 08.00. I was trying to play with content offsets on scrolling views, with no luck. Can you kindly explain me (or, at least, orient me) about this matter?

Thanks in advance

**Comment by gklka** [comment]
This is a feature which I need very much too.

**Comment by jumartin** [comment]
Hi, I've just added this functionality with a new property `hourRange` on `MGCDayPlannerView`. Check the last commits!

**Comment by gklka** [comment]
Looks nice, thank you! When can we expect a new CocoaPod release?
