### ISSUE TITLE
hello, how to disable the popover in the month view?

### ISSUE THREAD

**Issue by jy1989** [jumartin/Calendar#13]
Hi I just want to use the month view. and don't want to show anything when click the cell.
How to disable it?
Thank you very much.

**Comment by jumartin** [comment]
Hi,
In your `MGCMonthPlannerEKViewController` subclass, you can return NO from `monthPlannerView:shouldSelectEventAtIndex:date:`

**Comment by jy1989** [comment]
thanks for reply
