### ISSUE TITLE
CocoaPod release?

### ISSUE THREAD

**Issue by gklka** [jumartin/Calendar#19]
Hello!

Our app is using your library, and you included a few additions recently (being able to set colors, restrict timeframe) which we really need before the release. I see that you are actively improving the library currently. When do you plan to release a new CocoaPod version which includes these changes? Shall I wait for it or just use a git source in my project?

**Comment by jumartin** [comment]
Hi,
I definitely plan to release a new CocoaPod with version 2.0 within a few weeks (maybe 2 or 3), although I can't be really precise about the date... There are a few more changes I'm working on now, especially on the month view. If you are in a hurry, maybe the best is indeed to include the library directly. I think it's fairly stable, but it's difficult for me to test thoroughly every configuration. Any report is very welcome in that matter!

**Comment by gklka** [comment]
Thank you. If it inspires you, we can donate you a small amount for your efforts :)

**Comment by jumartin** [comment]
Also please note that version 2 will require iOS 8 or later, due to the use of the new presentation controllers. I hope that’s not a problem for you.
And thanks for the offer! ;)

**Comment by gklka** [comment]
iOS 8 is our target too. Do you have a paypal address maybe?

**Comment by jumartin** [comment]
Hi, yes I have a Paypal address, which is the same as the one on my profile. 
Thanks! In any case, it's already nice for me to know that this thing is useful for some people...

**Comment by gklka** [comment]
Thanks for the release. We have sent you a little amount of donation for your work.

**Comment by jumartin** [comment]
Thank you, I very much appreciate!
