### ISSUE TITLE
pod CalendarLib pulls 1.0 by default still

### ISSUE THREAD

**Issue by SixFiveSoftware** [jumartin/Calendar#24]
Thanks so much for providing this great repo! I was wondering why I saw a difference between what was pulled into my project than what I saw in the repo, and noticed in my Podfile.lock that it downloaded 1.0, even though 2.0 is what is listed on cocoapods.org. I specified a specific commit, and that worked, but I don't like that as a long-term solution. Am I missing something?

**Comment by jumartin** [comment]
Hi,
That's weird, I've just tried it and it works for me with with `pod 'CalendarLib' `
Did you run try to run `pod install` again?

**Comment by SixFiveSoftware** [comment]
Hey, thanks for the quick reply! Yea, a few times, but still no luck. Even created a new, blank project, and still pulled 1.0. I'm using CocoaPods 1.0.0 b6, if that helps. Think the CocoaPods version might be the culprit?

**Comment by jumartin** [comment]
Indeed, I think that might be it: I'm using 0.39 and everything's ok...

**Comment by SixFiveSoftware** [comment]
I'll try it on another machine here shortly and report back. Thanks for the info!

**Comment by SixFiveSoftware** [comment]
Jeez, I'm sorry for the delay, I forgot to get back to you sooner. I tried the other day on a VM I have of OS X that has CocoaPods 0.39, and sure enough, it worked just fine. Sorry for the trouble, but thanks for validating that it worked. Might be something for the README to add for users to be aware of? Anyway, great library, thank you for your hard work!

**Comment by jumartin** [comment]
Ok, thanks for checking!

**Comment by jumartin** [comment]
This seems to be fixed, and work as expected with the new release of CocoaPods 1.0.
