### ISSUE TITLE
I need you help!!!

### ISSUE THREAD

**Issue by Chris-Pan** [jumartin/Calendar#27]
Very thank you for your SDK. I got a problem that I need to page all  the weekView, it is just like google's tiny calendar,  it can scroll seven days when user scroll the screen, can you give me some tips to reach the same function? May you can provide a property set it ?  I am waiting for you message, thank you! this is the connect of google's tiny calendar [https://itunes.apple.com/us/app/tiny-calendar-sync-google/id514917848?mt=8](url)

**Comment by Chris-Pan** [comment]
any body here??

**Comment by jumartin** [comment]
Hi,
I'm not sure I understand exactly what you're trying to achieve. 
For paging, just set `pagingEnabled` to YES.

**Comment by Chris-Pan** [comment]
Thank you for your message! could I commumicate with you in Twitter? and my twitter number is "@1612498273New", thank you !!

**Comment by jumartin** [comment]
I'd rather keep this on GitHub if you don't mind. Also the discussion can interest others...

**Comment by Chris-Pan** [comment]
ok,I mean that you may set a property to scroll all week (if set this property, user can not scroll calendar(weekview I mean) day by day ). for reach this I try to set the 'scrollView's pageEnable = Yes ', not you provide the  'pagingEnabled' , it is can achieve my goal, but it's always some bug in it. and now our project change this demand , so anyway , I just wanna say thank you guy!
