### ISSUE TITLE
Overriding default action when long-press

### ISSUE THREAD

**Issue by sebastienkb** [jumartin/Calendar#30]
Hi,

I'm new to this but your library looks very promising.
In your demo app, long-press invokes what I'm assuming is the popup of the default event view. Can we override this to something else? For the sake of an example, how can one override this to an NSLog presenting the new date?

Thanks

**Comment by jumartin** [comment]
Hi,

In the day planner, whenever a long-press event happens **on an event view**, the following delegate method gets called (providing `canMoveEvents` property is set, which is the default) : 

`-dayPlannerView:shouldStartMovingEventOfType:atIndex:date:`

When a long-press happens **on an empty space**, those get called (providing `canCreateEvents` is set) :

`-dayPlannerView:viewForNewEventOfType:atDate:`

followed by:

`-dayPlannerView:canCreateNewEventOfType:atDate:`

Similar methods are available for the month planner. You can easily  override them in your view controller subclass.

**Comment by sebastienkb** [comment]
Thank you for your input, I will try this as soon as I get back to my desk!

**Comment by sebastienkb** [comment]
Hi,

I'm a little confused right now.
I indeed see that `MGCDayPlannerView.m` uses its private method `handleLongPress`, which will eventually fire `shouldStartMovingEventOfType` from `MGCDayPlannerViewDataSource`.
So when I read `MGCDayPlannerViewDataSource` I see 
> An object that adopts the MGCDayPlannerViewDataSource protocol is responsible for providing the data and views.
So if I want to achieve the task at hand (NSLog the long-pressed date) from the Demo app (i.e. delegating `MGCDayPlannerViewDataSource` inside `MainViewController () < >`, how can I provide the data? As said in #31 I had `setEvents:(NSArray *)` in mind, but obviously I'm not thinking correctly.

Do you have sample code for "providing the data" with hardcoded values?

**Comment by sebastienkb** [comment]
Understood now, thanks. I see now that the library is actually similar to UITableView but the learning curve is longer than UITableView ;-)
