### ISSUE TITLE
Multi-day views issue on dayPlannerView

### ISSUE THREAD

**Issue by sebastienkb** [jumartin/Calendar#32]
Hi,

I am trying to use `viewForEventOfType:` within my controller which extends from `MGCDayPlannerViewController`. I only use `MGCTimedEventType`s and they work fine as long as they don't overlap days. If they overlap, all next days plus same day appear as all-day, see attachment.

I do set the range with `dateRangeForEventOfType:`, where I'm essentially returning `[MGCDateRange dateRangeWithStart:event.beginDate end:event.endDate];`

Last place I can imagine go wrong is the `numberOfEventsOfType:` method. Currently I use an NSDictionary<NSString *, NSArray *>, where the key is the format string of the **begin date** of the event (so no knowledge of overlapping) and the value is the array of events starting at that day.
What does this method expect exactly? if I have only one event from 1 July 13:00 to 3 July 19:00; does it mean that:
1 July returns 1
2 July returns 1
3 July returns 1
?

Thanks a lot

![img_0136](https://cloud.githubusercontent.com/assets/5427924/16451792/69368eec-3e05-11e6-8f4f-a5ce5951a6f4.PNG)

**Comment by jumartin** [comment]
Hi, 
Indeed, `numberOfEventsOfType:atDate:` is expected to return 1 **for each day spanned by the event** (1, 2 and 3 of July in your example), and not only for the starting day.
Then, `dateRangeForEventOfType:atIndex:date:` should return the complete range for each (i.e. 1 July 13:00 to 3 July 19:00).
I hope this helps - I admit this should be better documented. I'll try to give an example in the next release.

**Comment by sebastienkb** [comment]
Hi,

Thanks for your quick reply!
I have applied your suggested changes (i.e. adding the reference in my dictionary for each day it is part of), and the timed events show fine, but now also full-day events seem to appear corresponding to the date minus the end date.

In which cases are full-day events generated? Is there a way where I can suppress displaying any full-day event (with other datasource or delegate methods)?

![img_5863](https://cloud.githubusercontent.com/assets/5427924/16518412/e3b1ae76-3f82-11e6-9360-9cf457025981.PNG)

**Comment by jumartin** [comment]
If you don't want any all-day event to show up, then return 0 when asked for the number of all-day events...

```
- (NSInteger)dayPlannerView:(MGCDayPlannerView*)view numberOfEventsOfType:(MGCEventType)type atDate:(NSDate*)date {
	if (type == MGCAllDayEventType) { return 0; }
    .....
}
```

**Comment by sebastienkb** [comment]
Now that you mention it, I feel silly. Thank you for your response!
