### ISSUE TITLE
grey row at the top of dayPlannerView

### ISSUE THREAD

**Issue by Wojtek1234** [jumartin/Calendar#38]
Hello, thanks for your library, it is very cool and quite easy to customize.
I have one problem. Is there any possibility to get rid of that grey row at the top of day planner View ?
![screen shot 2016-08-11 at 18 44 14](https://cloud.githubusercontent.com/assets/6803251/17596882/b9b42c7a-5ff3-11e6-9ba1-79e500e97c02.png)

Many thanks

cheers
Wojtek

**Comment by jumartin** [comment]
Hi,
The grey row at the top is where all-day events are displayed. 
If you want to hide it, just set `showsAllDayEvents` property to NO.

**Comment by Wojtek1234** [comment]
Your the man 👍  Many thanks !!!

Cheers
