### ISSUE TITLE
How to set an alpha or remove this gray bar that appears under the header?

### ISSUE THREAD

**Issue by robertoferraz** [jumartin/Calendar#49]
I see in some of the screenshots on the repository that there is a transparent bar under the header, but when I add the calendar in my project there is always this gray bar that is not transparent. So I would like to know how to set an alpha on it, so I could actually put it to 0, if there is a way of removing it, even better.

See the screenshot with the bar:
<img width="311" alt="screen shot 2016-10-20 at 12 45 41" src="https://cloud.githubusercontent.com/assets/270483/19556799/23e099d4-96c3-11e6-8d24-b5cbb1fca348.png">

And with alpha as showed in the repository page:
![screen shot 2016-10-20 at 12 43 24](https://cloud.githubusercontent.com/assets/270483/19556743/d97021da-96c2-11e6-9235-a2afa795aca0.png)

**Comment by robertoferraz** [comment]
Just found that, this view is the All day events view. Closed

**Comment by dlucidone** [comment]
Any solutions to this

**Comment by shingsoso** [comment]
showsAllDayEvents should set to false
