### ISSUE TITLE
Side-by-side Events not drawing as intended

### ISSUE THREAD

**Issue by ezathashim** [jumartin/Calendar#6]
Julien:

really nice library. I am having an issue where events that are side-by-side do an odd overlap.

1) Image 1 - the event on the left overlaps with the one on the right. If I scroll from right-to-left, I can see that the appointment on the right creeps over to the next column (Image 2)

2) Image 3 - If I rotate the device, it redraws, but there seems to be a space between the 2 events

3) Image 4 - If I rotate back to portrait, the cells align properly

4) If I scroll the events vertically out of view, and then scroll them back in, they end up drawing like in 'Image 1' again.

Any ideas why this would be happening? Nothing in your code is immediately obvious. Also, I have an iPhone demo running. I could give it to you and you can tweak it to your liking.

Many thanks

- Ezat
![image 1](https://cloud.githubusercontent.com/assets/5372535/9747613/b6997286-564c-11e5-8010-c9cc0ff58b21.png)

![image 2](https://cloud.githubusercontent.com/assets/5372535/9747635/d5ba4ad2-564c-11e5-8fc6-84bebc8b9ee9.png)

![image 3](https://cloud.githubusercontent.com/assets/5372535/9747646/ea23d7d6-564c-11e5-9129-e95d39247ffb.png)

![image 4](https://cloud.githubusercontent.com/assets/5372535/9747650/f4614864-564c-11e5-8c47-e805ab92ec88.png)

**Comment by mythodeia** [comment]
@ezathashim did you find a solution or was it an error in your code?

**Comment by ezathashim** [comment]
It appears to be something in my code, specifically my EventView subclass. My subclass uses autolayout of subviews which seems to be doing something bad.
