### ISSUE TITLE
Device Rotation Error

### ISSUE THREAD

**Issue by ezathashim** [jumartin/Calendar#7]
I am getting this error on device rotation when using single day display on iPhone.

'Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.'

I am not exactly sure how to fix it. I also got odd drawing artefacts on rotation animation - the displayed text in an eventView stretches out like it was written on silly-putty. 

Also, the day column does not expand properly during animation (when going from portrait to landscape)  so that it displays 2 columns instead of 1 column at the end of rotation.

**Comment by ezathashim** [comment]
OK, I've narrowed down the issue of the console message:

'Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.'

It occurs when rotating the MGCYearCalendarView. I'll poke around a bit more to figure out why this is happening.

**Comment by jumartin** [comment]
Thanks for the feedback!
Unfortunately I don't have time to look at it at the moment... Does this occur also on the iPad? 
As I said, the calendar is not ready yet for the iPhone. I hope I'll be able to work on it in the next few weeks.
